### ISSUE TITLE
Severity "Success"

### ISSUE THREAD

**Issue by nevrome** [co-log/co-log-core#21]
I wonder if a constructor `Success` would be useful for the `Severity` data type to distinguish critical operations that completed successfully in the log stream. Of course all of this can go into `Info`, but I feel an extra layer would help.

Green might be a fitting colour, if you're willing to consider this addition.

**Comment by alaendle** [comment]
Sorry for the late response, however to be honest I don't believe that `Success` is general enough to be added to `co-log-core`. 

- For me failing/succeeding seems to be a orthogonal aspect and is not really related to the severity of a message
- Also if you really like you to add this on a severity level you could use a custom severity in conjunction with `co-log` (https://github.com/co-log/co-log/blob/f7049209d1c50f0544f864adda187c9d52c1baac/src/Colog/Message.hs#L107)
- Or maybe better add a custom field like it is done in https://github.com/co-log/co-log/blob/main/src/Colog/Message.hs for `posixTime` and `threadId`.
- Also note that other frameworks don't provide such a severity (e.g. https://logging.apache.org/log4j/2.x/javadoc/log4j-api/index.html or https://learn.microsoft.com/de-de/dotnet/api/microsoft.extensions.logging.loglevel?view=dotnet-plat-ext-7.0)

**Comment by nevrome** [comment]
Alright - thanks for considering it :+1:
